SMSproj2/Controllers/smsMessageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SMSproj2.Models;

namespace SMSproj2.Controllers
{
    
    public class smsMessageController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(SMSMessage msg)
        {
            try
            {
                ViewData["phoneNumber"] = msg.phoneNumber;
                ViewData["smsMessageTest"] = msg.smsMessageText;
                msg.sendMessage();
                ViewData["status"] = msg.status;
                return View("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SMSproj2/Controllers/webEmailController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SMSproj2.Models;


namespace SMSproj2.Controllers
{
    public class webEmailController : Controller
    {
        // GET: webEmailController
        public ActionResult Index()
        {
            return View();
        }

       
        // GET: webEmailController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: webEmailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebEmail msg)
        {
            try
            {
                ViewData["oRecipients"] = msg.toRecipients;
                ViewData["subject"] = msg.subject;
                ViewData["emailMsg"] = msg.emailMsg;
                msg.sendWebMail();
                ViewData["status"] = msg.status;
                return View("Index");
                //return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

       
    }
}

SMSproj2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMSproj2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SMSproj2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SMSproj2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="smsMessage" asp-action="Create">Send SMS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="webEmail" asp-action="Create">Send Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SMSproj2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
      
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>